# Generated by Django 3.2.13 on 2023-01-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField(blank=True, default=0, null=True, verbose_name='Total Cost')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, default=0, null=True, verbose_name='Cost')),
                ('process_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='core.processchain', verbose_name='Process Chain')),
            ],
        ),
    ]
